export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES"

export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES"

export const CURRENT_SONG_PLAYING = "CURRENT_SONG_PLAYING"

export const SONG_IS_PLAYING = "SONG_IS_PLAYING"

export const FETCH_ARTIST_SEARCH = "FETCH_ARTIST_SEARCH"

export const FETCH_ARTIST_ERROR = "FETCH_ARTIST_ERROR"

export const FETCH_ARTIST_LOADING = "FETCH_ARTIST_LOADING"

export const ARTIST_SEARCH_LENGTH = "ARTIST_SEARCH_LENGTH"